In [1]:
import pandas as pd
import os 
import scanpath
import math
import numpy as np

In [2]:
def get_file_data(file):
    file_path = os.path.join('./data/scanpaths/', file)
    df = pd.read_csv(file_path, delimiter='\t')
    cols = df.columns.to_list()
    df['file'] = file.replace("_scanpath.tsv", "")
    df = df[['file'] + cols]
    return df

In [3]:
files = [i for i in os.listdir('./data/scanpaths/')]
files = [i for i in files if ('reader85_p0' in i)|('reader72_p0' in i)]
master_df = get_file_data(files[0])

for i  in  files[1:]:
    master_df = pd.concat([master_df, get_file_data(i)])

In [13]:
master_df

,file,fixation_index,text_domain,trial,acc_bq_1,acc_bq_2,acc_bq_3,acc_tq_1,acc_tq_2,acc_tq_3,...,reader_id,text_id,x,y,word_index_in_text,sent_index_in_text,char_index_in_text,word,character,text_id_numeric
0,reader85_p0,1,physics,10,0,0,1,0,1,0,...,85,p0,86.9,55.1,1,1,1,Ein,E,6
1,reader85_p0,2,physics,10,0,0,1,0,1,0,...,85,p0,189.8,66.4,2,1,7,Zyklotron,l,6
2,reader85_p0,3,physics,10,0,0,1,0,1,0,...,85,p0,332.8,65.2,3,1,17,besteht,e,6
3,reader85_p0,4,physics,10,0,0,1,0,1,0,...,85,p0,528.6,52.5,6,1,28,flachen,f,6
4,reader85_p0,5,physics,10,0,0,1,0,1,0,...,85,p0,586.0,48.9,6,1,32,flachen,h,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,reader72_p0,532,physics,11,0,0,0,0,0,0,...,72,p0,1347.5,942.8,174,6,1094,extrahiert,i,6
532,reader72_p0,533,physics,11,0,0,0,0,0,0,...,72,p0,1189.7,945.5,173,6,1084,Ablenkfeld,f,6
533,reader72_p0,534,physics,11,0,0,0,0,0,0,...,72,p0,1331.0,944.3,174,6,1093,extrahiert,h,6
534,reader72_p0,535,physics,11,0,0,0,0,0,0,...,72,p0,1473.5,938.6,175,6,1102,werden,e,6
535,reader72_p0,536,physics,11,0,0,0,0,0,0,...,72,p0,1590.1,943.2,176,6,1109,können,n,6

In [4]:
master_df.columns

Index(['file', 'fixation_index', 'text_domain', 'trial', 'acc_bq_1',
       'acc_bq_2', 'acc_bq_3', 'acc_tq_1', 'acc_tq_2', 'acc_tq_3',
       'fixation_duration', 'next_saccade_duration',
       'previous_saccade_duration', 'version', 'line', 'roi',
       'char_index_in_line', 'original_fixation_index', 'is_fixation_adjusted',
       'reader_id', 'text_id', 'fixation_position_x', 'fixation_position_y',
       'word_index_in_text', 'sent_index_in_text', 'char_index_in_text',
       'word', 'character', 'text_id_numeric'],
      dtype='object')

In [5]:
master_df = master_df.rename(columns={'fixation_position_x':'x', 'fixation_position_y':'y', 'fixation_duration':'duration'})
s = master_df[master_df['file'] == 'reader85_p0'][['x', 'y', 'duration']]
t = master_df[master_df['file'] == 'reader72_p0'][['x', 'y', 'duration']]

In [9]:
center_x = master_df['x'].median()
center_y = master_df['y'].median()

distance = math.sqrt(pow(center_x,2) + pow(center_y,2))
score, path, alignment  = scanpath.rscasim(s, t, center_x, center_y, distance, 1, modulator=0.83)

461 536
460 535
459 534
458 534
457 533
456 532
455 531
454 530
453 529
452 528
452 527
451 526
450 525
450 524
449 523
448 523
447 522
446 521
445 520
444 520
443 519
442 518
441 517
441 516
441 515
440 514
439 513
438 512
437 511
436 510
435 509
435 508
434 507
434 506
434 505
434 504
434 503
433 502
432 501
432 500
431 499
431 498
430 497
430 496
430 495
429 494
428 493
427 492
426 491
426 490
426 489
426 488
425 487
424 486
424 485
423 484
422 484
421 484
420 484
419 484
418 484
417 484
416 484
415 484
414 484
413 483
412 483
411 483
410 483
409 483
408 483
407 483
406 482
405 482
404 482
403 482
402 482
401 481
400 481
399 481
398 481
397 481
396 480
395 479
394 478
393 477
392 476
391 476
390 476
389 476
388 476
387 476
386 476
385 476
384 476
383 476
382 476
381 476
380 476
379 476
378 476
377 476
376 476
375 476
374 476
373 476
372 476
371 476
370 476
369 476
368 476
367 476
366 476
365 476
364 476
363 476
362 476
361 476
360 476
359 476
358 476
357 476
356 476
355 476
354 476
353 476
352 476
351 476
350 476
349 476
348 476
347 476
346 476
345 476
344 476
343 476
342 476
341 476
340 476
339 476
338 476
337 476
336 476
335 476
334 476
333 476
332 476
331 476
330 476
329 476
328 476
327 476
326 476
325 476
324 476
323 476
322 476
321 476
320 476
319 476
318 476
317 476
316 476
315 476
314 476
313 476
312 476
311 476
310 476
309 476
308 476
307 476
306 476
305 476
304 476
303 476
302 476
301 476
300 476
299 476
298 476
297 476
296 476
295 476
294 476
293 476
292 476
291 476
290 476
289 476
288 476
287 476
286 476
285 476
284 476
283 476
282 476
281 476
280 476
279 476
278 476
277 476
276 476
275 476
274 476
273 476
272 476
271 476
270 476
269 476
268 476
267 476
266 476
265 476
264 476
263 476
262 476
261 476
260 476
259 476
258 476
257 476
256 476
255 476
254 476
253 476
252 476
251 476
250 476
249 476
248 476
247 476
246 476
245 476
244 476
243 476
242 476
241 476
240 476
239 476
238 476
237 476
236 476
235 476
234 476
233 476
232 476
231 476
230 476
229 476
228 476
227 476
226 476
225 476
224 476
223 476
222 475
221 474
221 473
221 472
221 471
221 470
221 469
220 468
220 467
219 466
219 465
218 464
218 463
218 462
217 461
216 460
216 459
215 458
215 457
214 456
213 455
212 454
212 453
212 452
211 451
210 450
209 449
208 448
207 447
207 446
207 445
207 444
206 443
206 442
205 441
205 440
205 439
204 438
204 437
203 436
203 435
202 434
201 433
201 432
200 431
199 430
198 429
198 428
198 427
198 426
198 425
198 424
198 423
197 422
197 421
196 420
196 419
196 418
195 417
195 416
194 415
193 414
192 413
192 412
192 411
192 410
191 409
191 408
191 407
190 406
190 405
190 404
189 403
189 402
188 401
187 400
186 399
185 398
184 397
183 396
183 395
183 394
182 393
181 392
180 391
179 390
178 389
177 388
177 387
176 386
175 385
175 384
174 383
173 382
173 381
173 380
173 379
172 378
172 377
171 376
171 375
170 374
169 373
168 372
167 371
166 370
165 369
165 368
165 367
165 366
164 365
163 365
162 364
161 363
160 362
160 361
160 360
160 359
160 358
159 357
159 356
158 355
157 354
156 353
155 353
154 352
153 351
153 350
152 349
151 348
151 347
150 346
149 345
149 344
149 343
149 342
149 341
149 340
149 339
149 338
149 337
149 336
149 335
149 334
149 333
148 332
148 331
148 330
148 329
148 328
148 327
148 326
147 325
146 324
146 323
145 322
144 321
143 320
143 319
143 318
142 317
142 316
141 315
141 314
141 313
140 312
140 311
140 310
139 309
138 308
138 307
137 306
136 305
135 304
135 303
134 302
133 301
133 300
133 299
132 298
132 297
131 296
131 295
130 294
130 293
130 292
129 291
129 290
129 289
129 288
129 287
128 286
128 285
128 284
128 283
128 282
128 281
127 280
126 279
125 278
124 277
123 277
122 277
121 277
120 276
119 275
119 274
119 273
119 272
118 271
117 270
117 269
117 268
116 267
115 266
114 265
113 264
112 263
111 262
111 261
110 260
110 259
110 258
109 257
108 256
108 255
108 254
108 253
107 252
106 251
106 250
105 249
105 248
104 247
104 246
103 245
103 244
102 243
101 242
100 241
99 240
98 239
97 238
96 237
96 236
95 235
95 234
95 233
95 232
95 231
95 230
95 229
94 228
94 227
93 226
92 225
91 225
90 224
89 223
89 222
89 221
89 220
89 219
89 218
89 217
88 216
88 215
88 214
88 213
88 212
88 211
88 210
88 209
87 208
86 207
86 206
86 205
85 204
85 203
84 202
83 201
83 200
83 199
82 198
82 197
82 196
82 195
81 194
80 193
79 192
78 191
78 190
78 189
78 188
78 187
78 186
78 185
78 184
78 183
78 182
78 181
78 180
78 179
78 178
78 177
78 176
77 175
77 174
77 173
77 172
76 171
75 170
74 169
73 169
72 168
71 167
71 166
71 165
71 164
71 163
71 162
71 161
71 160
71 159
71 158
71 157
71 156
71 155
71 154
71 153
71 152
71 151
71 150
71 149
71 148
71 147
71 146
71 145
71 144
71 143
71 142
71 141
71 140
71 139
71 138
71 137
71 136
71 135
71 134
71 133
71 132
70 131
69 130
68 129
67 128
66 127
65 126
65 125
64 124
64 123
63 122
62 121
61 120
60 119
59 118
58 117
57 117
56 117
55 116
54 116
53 116
52 116
51 116
50 116
49 116
48 116
47 115
46 114
46 113
45 112
45 111
45 110
44 109
44 108
44 107
44 106
44 105
44 104
43 103
42 102
41 101
40 100
40 99
39 98
38 97
38 96
37 95
37 94
37 93
37 92
37 91
36 90
36 89
36 88
36 87
36 86
36 85
36 84
36 83
36 82
36 81
36 80
36 79
35 78
34 77
34 76
34 75
33 74
33 73
33 72
33 71
33 70
33 69
33 68
32 67
31 66
31 65
31 64
31 63
31 62
31 61
31 60
31 59
31 58
31 57
31 56
31 55
30 54
29 54
28 53
27 53
26 52
26 51
26 50
26 49
25 48
24 47
23 46
22 45
21 44
21 43
21 42
21 41
21 40
21 39
21 38
21 37
20 36
19 35
19 34
19 33
18 32
17 32
16 32
15 31
15 30
14 29
13 28
12 27
12 26
12 25
11 24
11 23
11 22
11 21
10 20
10 19
10 18
10 17
10 16
10 15
9 14
8 13
7 12
6 11
5 10
5 9
4 8
3 7
2 6
2 5
2 4
2 3
2 2
1 1

In [11]:
pd.DataFrame(score)

,0,1,2,3,4,5,6,7,8,9,...,527,528,529,530,531,532,533,534,535,536
0,0.0,122.000000,309.000000,481.000000,606.000000,721.000000,853.000000,1073.000000,1250.000000,1711.000000,...,110399.000000,110560.000000,110739.000000,111041.000000,111376.000000,111549.000000,111726.000000,111997.000000,112270.000000,112440.000000
1,157.0,99.138090,286.138090,458.138090,583.138090,698.138090,830.138090,1050.138090,1227.138090,1688.138090,...,110376.138090,110537.138090,110716.138090,111018.138090,111353.138090,111526.138090,111703.138090,111974.138090,112247.138090,112417.138090
2,655.0,597.138090,481.963033,653.963033,778.963033,893.963033,1025.963033,1245.963033,1422.963033,1883.963033,...,110503.104360,110664.104360,110843.104360,111145.104360,111480.104360,111653.104360,111830.104360,112101.104360,112374.104360,112544.104360
3,879.0,821.138090,705.963033,745.000944,870.000944,942.501834,1074.501834,1274.752588,1451.752588,1912.752588,...,110448.411579,110609.411579,110788.411579,111090.411579,111425.411579,111598.411579,111775.411579,112046.411579,112319.411579,112489.411579
4,1071.0,1013.138090,897.963033,937.000944,1051.890948,1134.501834,1164.414334,1372.004980,1396.725040,1857.725040,...,110478.099700,110639.099700,110818.099700,111120.099700,111455.099700,111628.099700,111805.099700,112076.099700,112349.099700,112519.099700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,109393.0,109291.146649,109168.814751,109069.733004,109042.986254,108971.714877,108909.898809,108940.217074,109017.583906,109340.245379,...,154861.083503,154986.160096,155090.328931,155166.464487,155128.545517,155250.049263,155283.790850,155499.822375,155772.822375,155942.822375
458,109643.0,109541.146649,109418.814751,109319.733004,109292.986254,109221.714877,109159.898809,109190.217074,109267.583906,109590.245379,...,155111.083503,155236.160096,155340.328931,155416.464487,155378.545517,155295.722982,155472.722982,155418.537822,155691.537822,155861.537822
459,109780.0,109678.146649,109555.814751,109456.733004,109429.986254,109358.714877,109296.898809,109327.217074,109404.583906,109727.245379,...,155248.083503,155373.160096,155477.328931,155553.464487,155515.545517,155432.722982,155512.151930,155555.537822,155756.464616,155926.464616
460,110001.0,109899.146649,109776.814751,109677.733004,109650.986254,109579.714877,109517.898809,109548.217074,109625.583906,109948.245379,...,155469.083503,155594.160096,155698.328931,155774.464487,155736.545517,155653.722982,155733.151930,155776.537822,155741.429276,155911.429276
461,110202.0,110100.146649,109977.814751,109878.733004,109851.986254,109780.714877,109718.898809,109749.217074,109826.583906,110149.245379,...,155670.083503,155795.160096,155899.328931,155975.464487,155937.545517,155854.722982,155934.151930,155977.537822,155942.429276,155887.469321

In [12]:
alignment

         s      t        cost
0      0.0    0.0   99.138090
1      1.0    1.0  382.824943
2      NaN    2.0  172.000000
3      NaN    3.0  125.000000
4      NaN    4.0  115.000000
..     ...    ...         ...
746  456.0  532.0  124.197886
747  457.0  533.0  134.746972
748  458.0    NaN  137.000000
749  459.0  534.0  185.891454
750  460.0  535.0  146.040045

[751 rows x 3 columns]